DROP TABLE EMPLOYEE CASCADE;
DROP TABLE WORK CASCADE;
DROP TABLE REGION CASCADE;
DROP TABLE WORK_REGION CASCADE;

SELECT * FROM EMPLOYEE;
SELECT * FROM WORK;
SELECT * FROM WORK_REGION;
SELECT * FROM REGION;